---
name: GitHub Actions Demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Print hello
        run: echo "Hello from GitHub Actions!"

      - name: List files
        run: ls ${{ github.workspace }}
