name: CI Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Package artifact
        run: tar -czf build-artifact.tgz ./dist
        # Replace ./dist with your build output directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: build-artifact.tgz
