name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin' # or 'adopt', 'oracle', 'zulu'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Test with Maven
        run: mvn test
